models integration
aboutcode-org/ScoreCode pull request #5
Opened 2024-07-03 07:53 UTC by 404-geek

2024-07-22 15:04 UTC, AyanSinhaMahapatra commented
Are all the comments at https://github.com/nexB/ScoreCode/pull/4#pullrequestreview-2151001759 and https://github.com/nexB/ScoreCode/pull/1#pullrequestreview-2132216329 resolved?

2024-07-29 14:06 UTC, AyanSinhaMahapatra requested changes
@404-geek Thanks for the changes, looking much better, we are getting there.

2024-07-29 14:06 UTC, AyanSinhaMahapatra commented on README.rst
> +    data = GetScorecard(platform, org, repo)
```suggestion
    data = GetScorecard(platform="github.com", org="nexB", repo="scancode-toolkit")
```
Have this together.

2024-07-29 14:06 UTC, AyanSinhaMahapatra commented on pyproject.toml
> +name = "ScoreCode"
We already have this info as a manifest in `setup.cfg`, we should have one or the another, not both.

2024-07-29 14:06 UTC, AyanSinhaMahapatra commented on setup.cfg
> +sqlalchemy =
What is `sqlalchemy` used for?

2024-07-29 14:26 UTC, 404-geek commented on pyproject.toml
> +name = "ScoreCode"
I also thought the same but for some reason while i run "make dev" it is taking all dependencies from pyproject.toml

2024-07-29 14:29 UTC, 404-geek commented on setup.cfg
> +sqlalchemy =
removed, sorry didn't notice it

2024-07-29 14:30 UTC, 404-geek commented on README.rst
> +    data = GetScorecard(platform, org, repo)
Done

2024-08-19 14:30 UTC, AyanSinhaMahapatra commented on pyproject.toml
> +name = "ScoreCode"
Have you tried removing the `pyproject.toml` and only having the `setup.cfg` like in the skeleton?

2024-08-20 19:51 UTC, 404-geek commented on pyproject.toml
> +name = "ScoreCode"
have removed it [link](https://github.com/aboutcode-org/scorecode/pull/5/commits/63b335ddc3940e412e60363e506866305ceaf276#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

2024-08-23 08:51 UTC, AyanSinhaMahapatra requested changes
There are also some tests failing in azure:
You should modify https://github.com/aboutcode-org/scorecode/blob/main/azure-pipelines.yml#L14 to only run tests from the `tests` directory. So it would be `venv/bin/pytest -n 2 -vvs tests`

Also https://github.com/aboutcode-org/scorecode/blob/main/src/README.rst can be removed.

2024-08-23 08:51 UTC, AyanSinhaMahapatra commented on tests/test_skeleton_codestyle.py
>  # See https://aboutcode.org for more information about nexB OSS projects.
Can you remove this file? This is not required.

2024-08-23 08:51 UTC, AyanSinhaMahapatra commented on README.rst
> +    pip install scorecard
This is taken we have to choose something else:
https://pypi.org/project/scorecard/

Maybe `ossfscorecard`?

2024-08-23 08:51 UTC, AyanSinhaMahapatra commented on README.rst
> +    pip install scorecard
We also have to modify the package name in setup.cfg accordingly

2024-08-23 08:51 UTC, AyanSinhaMahapatra commented on setup.cfg
> -python_requires = >=3.8
We should keep these options as I think they are needed to create wheels/source archives for a release

2024-08-23 09:00 UTC, AyanSinhaMahapatra commented on src/ossf_scorecard/contrib/models.py
> +import attr
This should not be in `src/ossf_scorecard/contrib/models.py`, rather `src/ossf_scorecard/models.py`?

2024-08-23 09:15 UTC, AyanSinhaMahapatra commented on README.rst
> +    pip install scorecard
Sorry, this would just be `scorecode` which is there in setup.cfg

2024-08-23 09:26 UTC, AyanSinhaMahapatra commented
Let's also make sure all the code files have a notice and let's use this one everywhere: https://github.com/aboutcode-org/scorecode/blob/main/src/ossf_scorecard/__init__.py#L2

2024-08-23 12:15 UTC, AyanSinhaMahapatra approved these changes
LGTM! Thanks++ @404-geek 
Looking much better now.
Let's push a tag and release after merging! :rocket:

2024-08-23 12:17 UTC, merged